### ISSUE TITLE
Build Hex Package

### ISSUE THREAD

**Issue by zkessin** [triqng/triq#10]

**Comment by tuncer** [comment]
Sure, why not. How about we remove the `release-0.1.0` branch and then tag a release before introducing further behavioral changes? We should also write a changelog.

**Comment by zkessin** [comment]
i would rather call it 1.0, but otherwise that makes sense

**Comment by tuncer** [comment]
To be clear, `release-0.1.0` is a branch, and I suggest to remove it because it's unused and not a tag.

**Comment by tuncer** [comment]
Deleted obsolete branch.

**Comment by tuncer** [comment]
I think we should tag v0.8 or v0.9 and declare v1.0 once we've merged the various community enhancements and fixed any regresions that introduces. I prefer prefixing tags with `v` because that sorts them cleanly and it leaves open the option of maintaining a x.y branch (no prefix there). It's a convention used in many projects and makes the most sense, if there's no other org-wide scheme in already place.

**Comment by aerosol** [comment]
Hey folks, thanks for maintaining this project. 
I would love to evaluate it with some Elixir bindings. Is there anything blocking you from releasing a package?

**Comment by zkessin** [comment]
Not as far as I know, its just not been a priority. Feel free to set it up and send a pull request.

**Comment by aerosol** [comment]
Thanks @zkessin, will do. In touch with @tuncer already :)

**Comment by tuncer** [comment]
Let's tag the following releases:

- `v1.0` for the last commit before the fork diverged
- `v1.1` what's in master right now
- `v1.2` very soon, after all patches and tickets are resolved, together with the public announcement of the community maintained fork

**Comment by aerosol** [comment]
I've had not enough ☕️ this morning, and pushed some sloppy commits/tags, sorry.

Anyway, the package is up: https://hex.pm/packages/triq/1.0.2
