### ISSUE TITLE
Adding link at hex

### ISSUE THREAD

**Issue by bieniusa** [triqng/triq#72]
Hi,
could someone add a link to this repository on the hex page?
It took me quite a while to realise that the hex package is built on this repo and not on the original, but outdated one.

Thanks,
Annette

**Comment by tuncer** [comment]
Hi,

what was the address of the hex page? Maybe you can post a screenshot so that I can compare with what I see on my end.

When I load https://hex.pm/packages/triq, I see two entries under __Links__. It should be noted that the plan is to move to the https://gitlab.com/triq org before the first public announcement of the community fork. And I suppose this report could be interpreted as a signal to not delay the announcement any longer.

The links on the hex page are populated from the following lines in src/triq.app.src:

```
   {links, [{"GitHub", "https://github.com/triqng/triq"},
            {"GitLab", "https://gitlab.com/triqng/triq"}]}
```

**Comment by bieniusa** [comment]
Now I see it, too. Sorry for the confusion.

**Comment by tuncer** [comment]
No worries, it's the web, and I was totally expecting that the page didn't render the links in your browser. Gone are the days of HTML that loads and works predictably.
